### ISSUE TITLE
Flathub app listing wrong image order

### ISSUE THREAD

**Issue by GijsGoudzwaard** [flathub/com.github.gijsgoudzwaard.image-optimizer#4]
The images shown on the app detail page are in the wrong order.

https://flathub.org/apps/details/com.github.gijsgoudzwaard.image-optimizer

The second image should be first. As seen [here](https://github.com/GijsGoudzwaard/Image-Optimizer/blob/master/data/com.github.gijsgoudzwaard.image-optimizer.appdata.xml.in#L25) the welcome screen image is stated as the `default`.

**Comment by bilelmoussaoui** [comment]
It's a known issue on Flathub frontend https://github.com/flathub/linux-store-frontend/issues/80
